version: 2
updates:
  - package-ecosystem: "uv"
    directory: /
    schedule:
      interval: weekly
      day: "friday"
      time: "18:13"
      timezone: "America/New_York"
    ignore:
      - dependency-name: "uv-build"
    allow:
      - dependency-type: "direct"
