[python]
mypy = "MIT"
pip-audit = "Apache-2.0"
pytest = "MIT"
pytest-cov = "MIT"
requests = "Apache-2.0"
rich = "MIT"
ruamel-yaml = "MIT"
ruff = "MIT"
uv-build = "Apache-2.0 OR MIT"
zensical = "MIT"

[actions]
"actions/checkout" = "MIT"
"actions/configure-pages" = "MIT"
"actions/deploy-pages" = "MIT"
"actions/download-artifact" = "MIT"
"actions/setup-python" = "MIT"
"actions/upload-artifact" = "MIT"
"actions/upload-pages-artifact" = "MIT"
"aquasecurity/trivy-action" = "Apache-2.0"
"astral-sh/setup-uv" = "MIT"
"dependabot/fetch-metadata" = "MIT"
"extractions/setup-just" = "MIT"
"github/codeql-action/analyze" = "MIT"
"github/codeql-action/init" = "MIT"
"pypa/gh-action-pypi-publish" = "BSD-3-Clause"
