"""Argument parser for check command."""

import ipaddress as ipa
from argparse import _SubParsersAction

COMMAND_NAME = "check"


def load_command_args(sp: _SubParsersAction) -> None:
    """Assemble the argument parser."""
    msg = """
    Check whether an IP address appears in data generated by
    \"banip build\". Threat-feed addresses are included when their country
    is permitted by at least one named policy in banip.yaml. Explicit
    denylist and managed bot entries are not limited by country policies.
    """
    parser = sp.add_parser(name=COMMAND_NAME, description=msg)
    parser.add_argument(
        "ip_addresses",
        metavar="IP",
        nargs="*",
        type=ipa.ip_address,
        help=(
            "IPv4 or IPv6 addresses to check. When omitted, addresses "
            "are read interactively."
        ),
    )

    return
