"""Argument parser for check command."""

from argparse import _SubParsersAction

COMMAND_NAME = "check"


def load_command_args(sp: _SubParsersAction) -> None:
    """Assemble the argument parser."""
    msg = """
    Check whether an IP address appears in data generated by
    \"banip build\". For example, an IP address from a country not listed
    in banip.yaml may appear in ipsum.txt but not in the rendered
    blacklist. The rendered blacklist includes only countries listed in
    banip.yaml.
    """
    sp.add_parser(name=COMMAND_NAME, description=msg)

    return
